# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
desc "Upload release apk on firebase app distribution"
       lane :uploadApkToFirebase do // uploadApkToFirebase = this is lane name we will use to distribute our build
          gradle(
                  task: "assemble",
                  build_type: "Release",
                  properties: {
                      "android.injected.signing.store.file" => "/Users/tnluser/keystorefile",
                      "android.injected.signing.store.password" => "123456",
                      "android.injected.signing.key.alias" => "key0",
                      "android.injected.signing.key.password" => "123456",
                  }
          )
          firebase_app_distribution(
                  app: "1:783458988956:android:9d919911c0108c21134e59",
                  firebase_cli_token: "1//0gSPLKUke5lNQCgYIARAAGBASNwF-L9Ir4J5B71b6Y_RIVNx8Ttlyt75zWy-QiGGzaXn3pozF2C6XoudUgU9y8b4dFzKm4Mgtsoc",
                  release_notes_file: "release-notes.txt", // release notes file which should be created in project root directory
                  android_artifact_type: "APK",
                  android_artifact_path: "app/build/outputs/apk/release/app-release.apk",
                  groups: "Debug" // testers group name
          )
       end

